inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - tmp/**/*
    - "vendor/**/*"
    # Generated binstubs
    - bin/rake

Style/FrozenStringLiteralComment:
  Exclude:
    - "**/bin/*"
    - "**/exe/*"
    - "spec/**/*"

